version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:5000"
    environment:
      DB_IP: 192.168.50.112
      DB_USER: homechat
      DB_PASS: Markes

      KC_URL: http://192.168.50.113:8080
      KC_REALM: master
      KC_CLIENT_ID: sync-service
      KC_CLIENT_SECRET: 9HXt8xUlWyE5U3ijiAbkUG4PFuVfVByJ
    restart: unless-stopped

